### ISSUE TITLE
Website Updates 

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#11]
Change subhead text from “One Country. Two Sites” to “One Event. Two Start Times.”

Add social media buttons below registration buttons and “scroll down for more info” on top video.

![Image from iOS (1)](https://user-images.githubusercontent.com/3967702/79643006-0a6c4c80-815e-11ea-8e99-90cf49532df0.jpg)
![Image from iOS](https://user-images.githubusercontent.com/3967702/79643008-0b04e300-815e-11ea-9c1d-475a2cf66965.jpg)
Change roll overs for social media buttons so that text remains in white instead of slate.

**Comment by VwH387RXAF1m61wOtwuU** [comment]
is that what you wanted? done
