### ISSUE TITLE
Copy to Discord Channel

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#12]
A Promotional Scheme:  We can reach the 250MM Discord users by setting up a Discord Server like the website to send people to Eventbrite and register to get the Real Server Link to join the Real Startup Weekend

https://discord.gg/zqG3JG

DiscordDiscord
Join the Startup Weekend Remote USA Discord Server!
Check out the Startup Weekend Remote USA community on Discord - hang out with 1 other members and enjoy free voice and text chat.(11 kB)
https://cdn.discordapp.com/icons/701171043632676886/0181e1972d0e283f4df9552eee409f3c.jpg?size=256

**Comment by VwH387RXAF1m61wOtwuU** [comment]
Missing exactly what you are wanting to do here? still not home, will be back soon.

**Comment by kopcho** [comment]
I want a landing page.  With no ability to do anything but read it, become a member who can share it, but its purpose is just a target for Discord ads to push Discord users to the server.  Once on the server, be able to click through to the Eventbrite pages, just like the startupweekend.us
________________________________

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
