### ISSUE TITLE
Discord Funnel Text

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#13]
Here is the picture and the separate text file

[Discord Text.docx](https://github.com/SWremoteUSA/SWremoteUSA.github.io/files/4499947/Discord.Text.docx)
![Copy of DISCORD AD- Startup Weekend USA_ Covid19 (April 24-26)](https://user-images.githubusercontent.com/3967702/79696736-bdf73e80-823b-11ea-8679-fb5e78a032bc.png)

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
