### ISSUE TITLE
Trim the Video

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#2]
Complaints about the cooking theme, can we just trim that part out of the video until I can get another video to use, or do you have something else with a transparency?

**Comment by VwH387RXAF1m61wOtwuU** [comment]
i thought the whole video, which is very short is only about cooking, if you want to use the ad one that was in the same folder or the one from youtube, figure out and post back here and I will get it done, but whichever one needs the trans overlay like the one he did this morning

**Comment by VwH387RXAF1m61wOtwuU** [comment]
NA
