### ISSUE TITLE
Add "Justin Williams Co" logo to website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#22]
![g5256 - IEEE Tucson](https://user-images.githubusercontent.com/64045666/79821895-c25b4e80-8344-11ea-9ffa-466ccb8071a2.png)

Link logo to this url: https://www.linkedin.com/in/justinwilliamsco/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
