### ISSUE TITLE
Explainer Video addition

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#3]
https://youtu.be/Csa_k3jKorw

Let's add this to the website.  Seems to be a lot of ideas on what should be there, so, work with Eric on placement.

Let me know if the YouTube link is all you need, if you need the mp4 I can get that to you.

**Comment by VwH387RXAF1m61wOtwuU** [comment]
I will download as mp4 from youtube, I will put under the Event title, if they want it moved, then I will move it

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
