### ISSUE TITLE
Revise three tiers for Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#39]
Finalized three tiers for Partners:

1. Global 
- Google for Startups (is that in there)
- neustar
- Differential Ventures
- Adobe Spark
- Upwork
- Wiley
- GEN

2. National (logos to come)

3. Community 
-Everybody else

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done, but need Wiley and Google entered as seperate GH issues with logos and website links
