### ISSUE TITLE
Add the Explainer Video Under the Headline

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#4]
Global Online Startup Weekend Unite to Fight COVID-19 USA
[add explainer video here, the 1min version]
Stay Home, Work Together. Change The World.

https://www.dropbox.com/sh/w3ywn4mtqjm3smb/AACgjkB_3xe4N7HX7bxyts1ua?dl=0

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
