### ISSUE TITLE
Add "Gaming Insomniacs" logo to National partners tier on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#40]
![Gaming_Insomniacs_Logo](https://user-images.githubusercontent.com/64045666/80004492-3c8bf000-8477-11ea-8614-be6973f47a1e.jpg)

Link: https://www.gaminginsomniacs.org/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
