### ISSUE TITLE
Replace Adobe Spark logo with new logo

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#43]
![adobe spark](https://user-images.githubusercontent.com/64045666/80029894-512eaf00-849c-11ea-8595-d838c74ba086.png)

Link: https://spark.adobe.com/sp/?_techstars_|_unite_against_covid-19=&r=techstarsblog_techstarsadobe_

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
