### ISSUE TITLE
Add "Freestyle" logo to Community Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#44]
![MAIN LOGO ON WHITE - Jared Muenks](https://user-images.githubusercontent.com/64045666/80056571-65dd6800-84d9-11ea-9ebe-afb14fb8dd10.png)

Link: https://livefreestyle.co/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
