### ISSUE TITLE
Add "Matanuska Telephone Association" logo to Community Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#45]
![mta clean logo - Hezekiah Holland](https://user-images.githubusercontent.com/64045666/80057345-2adc3400-84db-11ea-94fd-fb6069b42f5f.png)

Link: https://www.mtasolutions.com/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
