### ISSUE TITLE
Add "Battery Low Interactive Ltd." logo to Community Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#50]
![BLI Logo (1) - Dewan Tarikul Mannan](https://user-images.githubusercontent.com/64045666/80150918-1137fc80-856e-11ea-9ac0-5b6b6f8ee27e.png)

Link: https://batterylowinteractive.com/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
