### ISSUE TITLE
Add "Pursuit Nutrition & Training Center" logo to Community Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#51]
![PURSUIT LOGO - Kerianne Los](https://user-images.githubusercontent.com/64045666/80152108-f1a1d380-856f-11ea-9b10-e759362d6978.jpeg)

Link: https://www.pursuit.fit

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
