### ISSUE TITLE
Add "Social Sector Network, LLC" logo to Community Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#52]
![Social Sector Network (5) - Conor Flynn](https://user-images.githubusercontent.com/64045666/80152686-ff0b8d80-8570-11ea-9fe4-39cc660b8e5f.jpg)
 
Link: https://socialsectornetwork.com

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
