### ISSUE TITLE
Livestream Updates for Website

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#63]
Change the button text to read "Registration Closes 12am Friday"
...early Friday I want that link to change to startupweekend.us/stream and the text changed to "Watch LIVESTREAM NOW!"

Livestream links - East Kickoff, West Kickoff, and Final Presentations to linked on startupweekend.us:
All-hands East, All-hands West links to be distributed to participants - first all-hands is at 8:30pm Friday

East Kickoff: https://www.youtube.com/watch?v=NBPxA-cRbdE
West Kickoff: https://www.youtube.com/watch?v=SKgwWyItHVs
All-hands East: https://www.youtube.com/watch?v=_ODcFjeDdfE
All-hands West: https://www.youtube.com/watch?v=ElZVsk0epTY
Tech Check: https://www.youtube.com/watch?v=bgyi2S2dTB8
Final Presentations: https://www.youtube.com/watch?v=bwgxHZWP7JI

**Comment by VwH387RXAF1m61wOtwuU** [comment]
dup
