### ISSUE TITLE
Add "Students Council of Gjilan" logo to Community Partners in website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#65]
![kngjlogo - esma fera](https://user-images.githubusercontent.com/64045666/80230453-d2a25080-8606-11ea-9f65-3b6b41ead5c2.jpg)

Link: https://www.instagram.com/kngj.gjilan/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
