### ISSUE TITLE
Add "Collectiveffort" logo to National Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#66]
![Logo (long BO)-01 - Jamel Mosely](https://user-images.githubusercontent.com/64045666/80246045-9f6cbb00-8620-11ea-9031-f8bbfa7c1f11.png)

Link: http://collectiveffort.co

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
