### ISSUE TITLE
Add "Audra L. Gibson Studios" logo to Community Partners on website

### ISSUE THREAD

**Issue by jenwong520** [SWremoteUSA/SWremoteUSA.github.io#67]
![ALG Studios Logo Large Blue](https://user-images.githubusercontent.com/64045666/80251284-39853100-862a-11ea-8916-4abe2958c28c.png)

Link: https://www.facebook.com/AudraLGibsonStudios/

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
