### ISSUE TITLE
Update the button Alignment

### ISSUE THREAD

**Issue by kopcho** [SWremoteUSA/SWremoteUSA.github.io#7]
the East and West Buttons are offset (not aligned) on the mobile view
![Image from iOS (1)](https://user-images.githubusercontent.com/3967702/79378085-f506e080-7f19-11ea-9083-706274a02317.png)
![Image from iOS](https://user-images.githubusercontent.com/3967702/79378110-005a0c00-7f1a-11ea-8a88-3db15c121257.png)

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
