### ISSUE TITLE
 ASAP- add Cool Hunting logo to NATIONAL partnerships (this was missing!)

### ISSUE THREAD

**Issue by jblueproductions** [SWremoteUSA/SWremoteUSA.github.io#71]
[https://coolhunting.com/](url)

![COOL-HUNTING-R-1 (1)](https://user-images.githubusercontent.com/64032095/80310483-f7cec480-87a8-11ea-8198-9c3158a38c2a.png)

**Comment by VwH387RXAF1m61wOtwuU** [comment]
done
